services:
  web:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
      - ./site:/var/www/html
    networks:
      - app-network

  php:
    container_name: php
    extra_hosts:
      - "host.docker.internal:host-gateway"
    build: ./php
    volumes:
      - ./site:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/conf.d/custom-php.ini
    networks:
      - app-network

  db:
    image: mysql:latest
    container_name: mysql
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app-network
    env_file:
      - .env

  phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    networks:
      - app-network
    env_file:
      - .env

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog
    restart: always
    ports:
      - "8025:8025"
    networks:
      - app-network

  selenium:
    image: selenium/standalone-chrome:latest
    container_name: selenium
    ports:
      - "4444:4444"  # Porta para o Selenium Grid
      - "5900:5900"  # Porta para o VNC
    environment:
      - SE_VNC_PASSWORD=secret
    networks:
      - app-network
    shm_size: '2gb'  # Evita problemas de memória compartilhada no Chrome headless

networks:
  app-network:
    driver: bridge

volumes:
  db_data: {}
